<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; 

class IRSSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('irs')->insert([

            // ['id_irs' => 1, 
            // 'nim' => '24060122140169', 
            // 'nama' => 'Nabila Betari Anjani', 
            // 'jurusan' => 'Informatika',
            // 'semester' => 5, 
            // 'tahun_akademik' => '2024/2025', 
            // 'kodemk' => 'PAIK6501', 
            // 'namamk' => 'Pengembagan Berbasis Platform',
            // 'kelas' => 'C', 
            // 'sks' => 21, 
            // 'status' => 'pending', 
            // 'tanggal_pengajuan' => '2024-12-01',
            // 'tanggal_persetujuan' => null,
            // ],
            // ['id_irs' => 2, 
            // 'nim' => '24060122140169', 
            // 'nama' => 'Nabila Betari Anjani', 
            // 'jurusan' => 'Informatika',
            // 'semester' => 5, 
            // 'tahun_akademik' => '2024/2025', 
            // 'kodemk' => 'PAIK6502', 
            // 'namamk' => 'Komputasi Tersebar dan Paralel',
            // 'kelas' => 'C', 
            // 'sks' => 21, 
            // 'status' => 'pending', 
            // 'tanggal_pengajuan' => '2024-12-01',
            // 'tanggal_persetujuan' => null,
            // ],
            // ['id_irs' => 3, 
            // 'nim' => '24060122140169', 
            // 'nama' => 'Nabila Betari Anjani', 
            // 'jurusan' => 'Informatika',
            // 'semester' => 5, 
            // 'tahun_akademik' => '2024/2025', 
            // 'kodemk' => 'PAIK6503', 
            // 'namamk' => 'Sistem Informasi',
            // 'kelas' => 'C', 
            // 'sks' => 21, 
            // 'status' => 'pending', 
            // 'tanggal_pengajuan' => '2024-12-01',
            // 'tanggal_persetujuan' => null,
            // ],
            // ['id_irs' => 4, 
            // 'nim' => '24060122140169', 
            // 'nama' => 'Nabila Betari Anjani', 
            // 'jurusan' => 'Informatika',
            // 'semester' => 5, 
            // 'tahun_akademik' => '2024/2025', 
            // 'kodemk' => 'PAIK6504', 
            // 'namamk' => 'Proyek Perangkat Lunak',
            // 'kelas' => 'C', 
            // 'sks' => 21, 
            // 'status' => 'pending', 
            // 'tanggal_pengajuan' => '2024-12-01',
            // 'tanggal_persetujuan' => null,
            // ],
            // ['id_irs' => 5, 
            // 'nim' => '24060122140169', 
            // 'nama' => 'Nabila Betari Anjani', 
            // 'jurusan' => 'Informatika',
            // 'semester' => 5, 
            // 'tahun_akademik' => '2024/2025', 
            // 'kodemk' => 'PAIK6505', 
            // 'namamk' => 'Pembelajaran Mesin',
            // 'kelas' => 'C', 
            // 'sks' => 21, 
            // 'status' => 'pending', 
            // 'tanggal_pengajuan' => '2024-12-01',
            // 'tanggal_persetujuan' => null,
            // ],
            // ['id_irs' => 6, 
            // 'nim' => '24060122140169', 
            // 'nama' => 'Nabila Betari Anjani', 
            // 'jurusan' => 'Informatika',
            // 'semester' => 5, 
            // 'tahun_akademik' => '2024/2025', 
            // 'kodemk' => 'PAIK6702', 
            // 'namamk' => 'Teori Bahasa dan Otomata',
            // 'kelas' => 'C', 
            // 'sks' => 21, 
            // 'status' => 'pending', 
            // 'tanggal_pengajuan' => '2024-12-01',
            // 'tanggal_persetujuan' => null,
            // ],
            ['id_irs' => 7, 
            'nim' => '24060124130085', 
            'nama' => 'Meyta Rizki Khairunisa', 
            'jurusan' => 'Informatika',
            'semester' => 1, 
            'tahun_akademik' => '2024/2025', 
            'kodemk' => 'AIK21311', 
            'namamk' => 'Dasar Pemrograman',
            'kelas' => 'A', 
            'sks' => 3, 
            'status' => 'pending', 
            'tanggal_pengajuan' => '2024-12-01',
            'tanggal_persetujuan' => null,
            ],
            ['id_irs' => 8, 
            'nim' => '24060124130085', 
            'nama' => 'Meyta Rizki Khairunisa', 
            'jurusan' => 'Informatika',
            'semester' => 1, 
            'tahun_akademik' => '2024/2025', 
            'kodemk' => 'AIK21312', 
            'namamk' => 'Dasar Sistem',
            'kelas' => 'A', 
            'sks' => 3, 
            'status' => 'pending', 
            'tanggal_pengajuan' => '2024-12-01',
            'tanggal_persetujuan' => null,
            ],
        ]);
    }
}
