<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JadwalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data awal untuk tabel jadwal
        $jadwal = [
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6501',
                'namamk' => 'Pengembangan Berbasis Platform',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'A',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Senin',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6502',
                'namamk' => 'Komputasi Tersebar dan Paralel',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'B',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Senin',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6505',
                'namamk' => 'Pembelajaran Mesin',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'C',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Senin',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6504',
                'namamk' => 'Proyek Perangkat Lunak',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'D',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Senin',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6702',
                'namamk' => 'Teori Bahasa dan Otomata',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'A',
                'sks' => 3,
                'semester' => 5,
                'ruang_kuliah' => 'Zoom',
                'dosen_pengampu' => 'Dr. Siti Aminah',
                'koordinator' => null,
                'hari' => 'Senin',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 20,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6503',
                'namamk' => 'Sistem Informasi',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'A',
                'sks' => 3,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 202',
                'dosen_pengampu' => 'Dr. Rina Kartika',
                'koordinator' => null,
                'hari' => 'Senin',
                'mulai' => '13:00:00',
                'selesai' => '15:00:00',
                'kuota' => 30,
                'kurikulum' => '2018',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6501',
                'namamk' => 'Pengembangan Berbasis Platform',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'B',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Selasa',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6502',
                'namamk' => 'Komputasi Tersebar dan Paralel',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'C',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Selasa',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6505',
                'namamk' => 'Pembelajaran Mesin',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'D',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Selasa',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6504',
                'namamk' => 'Proyek Perangkat Lunak',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'A',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 107',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Selasa',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6702',
                'namamk' => 'Teori Bahasa dan Otomata',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'B',
                'sks' => 3,
                'semester' => 5,
                'ruang_kuliah' => 'Zoom',
                'dosen_pengampu' => 'Dr. Siti Aminah',
                'koordinator' => null,
                'hari' => 'Selasa',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 20,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6503',
                'namamk' => 'Sistem Informasi',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'B',
                'sks' => 3,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 202',
                'dosen_pengampu' => 'Dr. Rina Kartika',
                'koordinator' => null,
                'hari' => 'Selasa',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 30,
                'kurikulum' => '2018',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6501',
                'namamk' => 'Pengembangan Berbasis Platform',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'C',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Rabu',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6502',
                'namamk' => 'Komputasi Tersebar dan Paralel',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'D',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Rabu',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6505',
                'namamk' => 'Pembelajaran Mesin',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'A',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Rabu',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6504',
                'namamk' => 'Proyek Perangkat Lunak',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'B',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Rabu',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6702',
                'namamk' => 'Teori Bahasa dan Otomata',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'C',
                'sks' => 3,
                'semester' => 5,
                'ruang_kuliah' => 'Zoom',
                'dosen_pengampu' => 'Dr. Siti Aminah',
                'koordinator' => null,
                'hari' => 'Jumat',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 20,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6503',
                'namamk' => 'Sistem Informasi',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'C',
                'sks' => 3,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 202',
                'dosen_pengampu' => 'Dr. Rina Kartika',
                'koordinator' => null,
                'hari' => 'Rabu',
                'mulai' => '08:00:00',
                'selesai' => '10:00:00',
                'kuota' => 30,
                'kurikulum' => '2018',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6501',
                'namamk' => 'Pengembangan Berbasis Platform',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'D',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Kamis',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6502',
                'namamk' => 'Komputasi Tersebar dan Paralel',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'A',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Kamis',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6505',
                'namamk' => 'Pembelajaran Mesin',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'B',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Kamis',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6504',
                'namamk' => 'Proyek Perangkat Lunak',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'C',
                'sks' => 4,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 101',
                'dosen_pengampu' => 'Dr. Agus Santoso',
                'koordinator' => 'Dr. Budi Raharjo',
                'hari' => 'Kamis',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 40,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6702',
                'namamk' => 'Teori Bahasa dan Otomata',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'D',
                'sks' => 3,
                'semester' => 5,
                'ruang_kuliah' => 'Zoom',
                'dosen_pengampu' => 'Dr. Siti Aminah',
                'koordinator' => null,
                'hari' => 'Jumat',
                'mulai' => '13:00:00',
                'selesai' => '15:00:00',
                'kuota' => 20,
                'kurikulum' => '2020',
            ],
            [
                'prodi' => 'Informatika',
                'kodemk' => 'PAIK6503',
                'namamk' => 'Sistem Informasi',
                'jenis_mata_kuliah' => 'wajib',
                'jenis_pertemuan' => 'tatap_muka',
                'jenis_kelas' => 'reguler',
                'kelas' => 'D',
                'sks' => 3,
                'semester' => 5,
                'ruang_kuliah' => 'Ruang 202',
                'dosen_pengampu' => 'Dr. Rina Kartika',
                'koordinator' => null,
                'hari' => 'Kamis',
                'mulai' => '15:40:00',
                'selesai' => '17:40:00',
                'kuota' => 30,
                'kurikulum' => '2018',
            ],
        ];

        // Insert data ke tabel jadwal
        DB::table('jadwal')->insert($jadwal);
    }
}